# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db2.ui'
#
# Created: Mon Oct 10 03:25:22 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormDB2(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(899, 656)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 145))# 0, 0, 791, 141)) #0, 0, 771, 111
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.db2_enum_tab = QtGui.QWidget()
        self.db2_enum_tab.setObjectName(_fromUtf8("db2_enum_tab"))
        self.tabWidget_3 = QtGui.QTabWidget(self.db2_enum_tab)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 761, 119))# 761, 114
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 711, 88))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.db2_users_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.db2_users_checkBox.setObjectName(_fromUtf8("db2_users_checkBox"))
        self.gridLayout_6.addWidget(self.db2_users_checkBox, 2, 0, 1, 1)
        self.db2_roles_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.db2_roles_checkBox.setObjectName(_fromUtf8("db2_roles_checkBox"))
        self.gridLayout_6.addWidget(self.db2_roles_checkBox, 0, 1, 1, 1)
        self.db2_current_user_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.db2_current_user_checkBox.setObjectName(_fromUtf8("db2_current_user_checkBox"))
        self.gridLayout_6.addWidget(self.db2_current_user_checkBox, 0, 0, 1, 1)
        self.db2_privileges_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.db2_privileges_checkBox.setObjectName(_fromUtf8("db2_privileges_checkBox"))
        self.gridLayout_6.addWidget(self.db2_privileges_checkBox, 1, 0, 1, 1)
        self.db2_is_dba_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.db2_is_dba_checkBox.setObjectName(_fromUtf8("db2_is_dba_checkBox"))
        self.gridLayout_6.addWidget(self.db2_is_dba_checkBox, 1, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 701, 81))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.db2_columns_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.db2_columns_checkBox.setObjectName(_fromUtf8("db2_columns_checkBox"))
        self.gridLayout_7.addWidget(self.db2_columns_checkBox, 1, 0, 1, 1)
        self.db2_count_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.db2_count_checkBox.setObjectName(_fromUtf8("db2_count_checkBox"))
        self.gridLayout_7.addWidget(self.db2_count_checkBox, 0, 0, 1, 1)
        self.db2_tables_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.db2_tables_checkBox.setObjectName(_fromUtf8("db2_tables_checkBox"))
        self.gridLayout_7.addWidget(self.db2_tables_checkBox, 2, 0, 1, 1)
        self.db2_schema_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.db2_schema_checkBox.setObjectName(_fromUtf8("db2_schema_checkBox"))
        self.gridLayout_7.addWidget(self.db2_schema_checkBox, 0, 1, 1, 1)
        self.db2_dbs_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.db2_dbs_checkBox.setObjectName(_fromUtf8("db2_dbs_checkBox"))
        self.gridLayout_7.addWidget(self.db2_dbs_checkBox, 1, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab_6)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 222, 61))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.db2_dump_all_checkBox = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.db2_dump_all_checkBox.setAutoExclusive(True)
        self.db2_dump_all_checkBox.setObjectName(_fromUtf8("db2_dump_all_checkBox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.db2_dump_all_checkBox)
        self.db2_dump_checkBox = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.db2_dump_checkBox.setAutoExclusive(True)
        self.db2_dump_checkBox.setObjectName(_fromUtf8("db2_dump_checkBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.db2_dump_checkBox)
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.db2_search_checkBox = QtGui.QCheckBox(self.tab_7)
        self.db2_search_checkBox.setGeometry(QtCore.QRect(20, 10, 274, 17))
        self.db2_search_checkBox.setObjectName(_fromUtf8("db2_search_checkBox"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.tab_7)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(20, 30, 711, 61))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.db2_TBL_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.db2_TBL_checkBox.setObjectName(_fromUtf8("db2_TBL_checkBox"))
        self.gridLayout_8.addWidget(self.db2_TBL_checkBox, 1, 0, 1, 1)
        self.db2_DB_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.db2_DB_lineEdit.setObjectName(_fromUtf8("db2_DB_lineEdit"))
        self.gridLayout_8.addWidget(self.db2_DB_lineEdit, 0, 1, 1, 1)
        self.db2_DB_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.db2_DB_checkBox.setObjectName(_fromUtf8("db2_DB_checkBox"))
        self.gridLayout_8.addWidget(self.db2_DB_checkBox, 0, 0, 1, 1)
        self.db2_TBL_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.db2_TBL_lineEdit.setObjectName(_fromUtf8("db2_TBL_lineEdit"))
        self.gridLayout_8.addWidget(self.db2_TBL_lineEdit, 1, 1, 1, 1)
        self.db2_COL_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.db2_COL_checkBox.setObjectName(_fromUtf8("db2_COL_checkBox"))
        self.gridLayout_8.addWidget(self.db2_COL_checkBox, 1, 2, 1, 1)
        self.db2_COL_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.db2_COL_lineEdit.setObjectName(_fromUtf8("db2_COL_lineEdit"))
        self.gridLayout_8.addWidget(self.db2_COL_lineEdit, 1, 3, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab_8)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.db2_banner_checkBox = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.db2_banner_checkBox.setObjectName(_fromUtf8("db2_banner_checkBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.db2_banner_checkBox)
        self.db2_hostname_checkBox = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.db2_hostname_checkBox.setObjectName(_fromUtf8("db2_hostname_checkBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.db2_hostname_checkBox)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.db2_sql_query_checkBox = QtGui.QCheckBox(self.tab_10)
        self.db2_sql_query_checkBox.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.db2_sql_query_checkBox.setObjectName(_fromUtf8("db2_sql_query_checkBox"))
        self.db2_sql_query_lineEdit = QtGui.QLineEdit(self.tab_10)
        self.db2_sql_query_lineEdit.setGeometry(QtCore.QRect(230, 10, 491, 20))
        self.db2_sql_query_lineEdit.setObjectName(_fromUtf8("db2_sql_query_lineEdit"))
        self.db2_sqlshell_checkBox = QtGui.QCheckBox(self.tab_10)
        self.db2_sqlshell_checkBox.setGeometry(QtCore.QRect(10, 40, 201, 17))
        self.db2_sqlshell_checkBox.setObjectName(_fromUtf8("db2_sqlshell_checkBox"))
        self.db2_sqlfile_checkBox = QtGui.QCheckBox(self.tab_10)
        self.db2_sqlfile_checkBox.setGeometry(QtCore.QRect(10, 70, 221, 17))
        self.db2_sqlfile_checkBox.setObjectName(_fromUtf8("db2_sqlfile_checkBox"))
        self.db2_sqlfile_lineEdit = QtGui.QLineEdit(self.tab_10)
        self.db2_sqlfile_lineEdit.setGeometry(QtCore.QRect(232, 70, 491, 20))
        self.db2_sqlfile_lineEdit.setObjectName(_fromUtf8("db2_sqlfile_lineEdit"))
        self.tabWidget_3.addTab(self.tab_10, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.db2_brute_tables_checkBox = QtGui.QCheckBox(self.tab_9)
        self.db2_brute_tables_checkBox.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.db2_brute_tables_checkBox.setObjectName(_fromUtf8("db2_brute_tables_checkBox"))
        self.brute_columns_checkBox = QtGui.QCheckBox(self.tab_9)
        self.brute_columns_checkBox.setGeometry(QtCore.QRect(20, 100, 151, 17))
        self.brute_columns_checkBox.setObjectName(_fromUtf8("brute_columns_checkBox"))
        self.db2_brute_columns_checkBox_2 = QtGui.QCheckBox(self.tab_9)
        self.db2_brute_columns_checkBox_2.setGeometry(QtCore.QRect(10, 40, 151, 17))
        self.db2_brute_columns_checkBox_2.setObjectName(_fromUtf8("db2_brute_columns_checkBox_2"))
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.tabWidget.addTab(self.db2_enum_tab, _fromUtf8(""))
        self.db2_fingerprint_tab = QtGui.QWidget()
        self.db2_fingerprint_tab.setObjectName(_fromUtf8("db2_fingerprint_tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.db2_fingerprint_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 10, 751, 80))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.db2_fingerprint_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.db2_fingerprint_checkBox.setGeometry(QtCore.QRect(10, 30, 281, 17))
        self.db2_fingerprint_checkBox.setObjectName(_fromUtf8("db2_fingerprint_checkBox"))
        self.tabWidget.addTab(self.db2_fingerprint_tab, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.db2_users_checkBox.setText(_translate("Form", "Enumerate DBMS users", None))
        self.db2_roles_checkBox.setText(_translate("Form", "Enumerate DBMS users roles", None))
        self.db2_current_user_checkBox.setText(_translate("Form", "Retrieve DBMS current user", None))
        self.db2_privileges_checkBox.setText(_translate("Form", "Enumerate DBMS users privileges", None))
        self.db2_is_dba_checkBox.setText(_translate("Form", "Detect if  current user is DBA", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("Form", "Users", None))
        self.db2_columns_checkBox.setText(_translate("Form", "Enumerate DBMS database table columns", None))
        self.db2_count_checkBox.setText(_translate("Form", "Retrieve number of entries for table(s)", None))
        self.db2_tables_checkBox.setText(_translate("Form", "Enumerate DBMS database tables", None))
        self.db2_schema_checkBox.setText(_translate("Form", "Enumerate DBMS schema", None))
        self.db2_dbs_checkBox.setText(_translate("Form", "Enumerate DBMS databases", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("Form", "Databases", None))
        self.db2_dump_all_checkBox.setText(_translate("Form", "Dump all DBMS databases tables entries", None))
        self.db2_dump_checkBox.setText(_translate("Form", "Dump DBMS database table entries", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("Form", "Entries", None))
        self.db2_search_checkBox.setText(_translate("Form", "Search column(s), table(s) and/or database name(s)", None))
        self.db2_TBL_checkBox.setText(_translate("Form", "DBMS db tables to enumerate", None))
        self.db2_DB_checkBox.setText(_translate("Form", "DBMS db to enumerate", None))
        self.db2_COL_checkBox.setText(_translate("Form", "DBMS db columns to enumerate", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Form", "Search", None))
        self.db2_banner_checkBox.setText(_translate("Form", "Retrieve DBMS banner", None))
        self.db2_hostname_checkBox.setText(_translate("Form", "Retrieve DBMS server hostname", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Form", "Generic", None))
        self.db2_sql_query_checkBox.setText(_translate("Form", "SQL statement to be executed", None))
        self.db2_sqlshell_checkBox.setText(_translate("Form", "Prompt for an interactive SQL shell", None))
        self.db2_sqlfile_checkBox.setText(_translate("Form", "Execute SQL statements from given file", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("Form", "Custom", None))
        self.db2_brute_tables_checkBox.setText(_translate("Form", "Check of common tables", None))
        self.brute_columns_checkBox.setText(_translate("Form", "Check  of common columns", None))
        self.db2_brute_columns_checkBox_2.setText(_translate("Form", "Check  of common columns", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("Form", "Brute force", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.db2_enum_tab), _translate("Form", "Enumeration", None))
        self.db2_fingerprint_checkBox.setText(_translate("Form", "Extensive database management system fingerprint", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.db2_fingerprint_tab), _translate("Form", "Fingerprint", None))

