# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detection_old.ui'
#
# Created: Thu Oct 13 08:37:57 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Detection(object):
    def setupUi(self, Detection):
        Detection.setObjectName(_fromUtf8("Detection"))
#        Detection.resize(835, 539)
	Detection.resize(QtCore.QSize(QtCore.QRect(0,0,835, 539).size()).expandedTo(Detection.minimumSizeHint()))
        self.detection_discard_pushButton = QtGui.QPushButton(Detection)
        self.detection_discard_pushButton.setGeometry(QtCore.QRect(610, 400, 75, 23))
        self.detection_discard_pushButton.setObjectName(_fromUtf8("detection_discard_pushButton"))
        self.detection_save_pushButton = QtGui.QPushButton(Detection)
        self.detection_save_pushButton.setGeometry(QtCore.QRect(510, 400, 75, 23))
        self.detection_save_pushButton.setObjectName(_fromUtf8("detection_save_pushButton"))
        self.groupBox_3 = QtGui.QGroupBox(Detection)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 821, 41))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 22))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.url_label = QtGui.QLabel(self.formLayoutWidget)
        self.url_label.setObjectName(_fromUtf8("url_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.url_label)
        self.url_lineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.url_lineEdit.setObjectName(_fromUtf8("url_lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.url_lineEdit)
        self.output_groupBox = QtGui.QGroupBox(Detection)
        self.output_groupBox.setGeometry(QtCore.QRect(10, 360, 475, 60))
        self.output_groupBox.setCheckable(True)
        self.output_groupBox.setChecked(False)
        self.output_groupBox.setObjectName(_fromUtf8("output_groupBox"))
        self.output_dir_lineEdit = QtGui.QLineEdit(self.output_groupBox)
        self.output_dir_lineEdit.setGeometry(QtCore.QRect(190, 20, 241, 20))
        self.output_dir_lineEdit.setObjectName(_fromUtf8("output_dir_lineEdit"))
        self.output_dir_toolButton = QtGui.QToolButton(self.output_groupBox)
        self.output_dir_toolButton.setGeometry(QtCore.QRect(440, 20, 25, 19))
        self.output_dir_toolButton.setText(_fromUtf8(""))
        self.output_dir_toolButton.setObjectName(_fromUtf8("output_dir_toolButton"))
        self.output_dir_checkBox = QtGui.QCheckBox(self.output_groupBox)
        self.output_dir_checkBox.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.output_dir_checkBox.setChecked(True)
        self.output_dir_checkBox.setObjectName(_fromUtf8("output_dir_checkBox"))
        self.tabWidget_3 = QtGui.QTabWidget(Detection)
        self.tabWidget_3.setGeometry(QtCore.QRect(20, 60, 811, 281))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 251))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_19 = QtGui.QWidget()
        self.tab_19.setObjectName(_fromUtf8("tab_19"))
#        self.URI_checkBox = QtGui.QCheckBox(self.tab_19)
 #       self.URI_checkBox.setGeometry(QtCore.QRect(20, 60, 121, 17))
  #      self.URI_checkBox.setObjectName(_fromUtf8("URI_checkBox"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_19)
        self.textBrowser_2.setGeometry(QtCore.QRect(310, 10, 460, 70))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
#        self.textBrowser_4 = QtGui.QTextBrowser(self.tab_19)
 #       self.textBrowser_4.setGeometry(QtCore.QRect(520, 10, 256, 41))
  #      self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.eval_checkBox = QtGui.QCheckBox(self.tab_19)
        self.eval_checkBox.setGeometry(QtCore.QRect(20, 120, 271, 17))
        self.eval_checkBox.setObjectName(_fromUtf8("eval_checkBox"))
        self.eval_lineEdit = QtGui.QLineEdit(self.tab_19)
        self.eval_lineEdit.setGeometry(QtCore.QRect(310, 120, 461, 20))
        self.eval_lineEdit.setObjectName(_fromUtf8("eval_lineEdit"))
        self.label_2 = QtGui.QLabel(self.tab_19)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 111, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget_2.addTab(self.tab_19, _fromUtf8(""))
        self.tab_20 = QtGui.QWidget()
        self.tab_20.setObjectName(_fromUtf8("tab_20"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_20)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.data_radioButton = QtGui.QRadioButton(self.tab_20)
        self.data_radioButton.setObjectName(_fromUtf8("data_radioButton"))
        self.gridLayout_4.addWidget(self.data_radioButton, 0, 0, 1, 1)
        self.data_plainTextEdit = QtGui.QPlainTextEdit(self.tab_20)
        self.data_plainTextEdit.setPlainText(_fromUtf8(""))
        self.data_plainTextEdit.setObjectName(_fromUtf8("data_plainTextEdit"))
        self.gridLayout_4.addWidget(self.data_plainTextEdit, 0, 1, 1, 1)
        self.testparameter_checkBox = QtGui.QCheckBox(self.tab_20)
        self.testparameter_checkBox.setObjectName(_fromUtf8("testparameter_checkBox"))
        self.gridLayout_4.addWidget(self.testparameter_checkBox, 1, 0, 1, 1)
        self.testparameter_lineEdit = QtGui.QLineEdit(self.tab_20)
        self.testparameter_lineEdit.setObjectName(_fromUtf8("testparameter_lineEdit"))
        self.gridLayout_4.addWidget(self.testparameter_lineEdit, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_20, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.requestfile_checkBox = QtGui.QCheckBox(self.tab)
        self.requestfile_checkBox.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.requestfile_checkBox.setObjectName(_fromUtf8("requestfile_checkBox"))
        self.requestfile_toolButton = QtGui.QToolButton(self.tab)
        self.requestfile_toolButton.setGeometry(QtCore.QRect(550, 20, 25, 19))
        self.requestfile_toolButton.setText(_fromUtf8(""))
        self.requestfile_toolButton.setObjectName(_fromUtf8("requestfile_toolButton"))
        self.requestfile_lineEdit = QtGui.QLineEdit(self.tab)
        self.requestfile_lineEdit.setGeometry(QtCore.QRect(210, 20, 331, 20))
        self.requestfile_lineEdit.setObjectName(_fromUtf8("requestfile_lineEdit"))
        self.testparam_lineEdit = QtGui.QLineEdit(self.tab)
        self.testparam_lineEdit.setGeometry(QtCore.QRect(193, 59, 591, 20))
        self.testparam_lineEdit.setObjectName(_fromUtf8("testparam_lineEdit"))
        self.testparam_checkBox = QtGui.QCheckBox(self.tab)
        self.testparam_checkBox.setGeometry(QtCore.QRect(10, 60, 177, 17))
        self.testparam_checkBox.setObjectName(_fromUtf8("testparam_checkBox"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_22 = QtGui.QWidget()
        self.tab_22.setObjectName(_fromUtf8("tab_22"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_22)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 80, 381, 51))
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setChecked(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.user_agent_lineEdit = QtGui.QLineEdit(self.groupBox_10)
        self.user_agent_lineEdit.setGeometry(QtCore.QRect(180, 20, 191, 20))
        self.user_agent_lineEdit.setObjectName(_fromUtf8("user_agent_lineEdit"))
        self.user_agent_checkBox = QtGui.QCheckBox(self.groupBox_10)
        self.user_agent_checkBox.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.user_agent_checkBox.setObjectName(_fromUtf8("user_agent_checkBox"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_22)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 10, 781, 51))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.host_header_checkBox = QtGui.QCheckBox(self.groupBox_11)
        self.host_header_checkBox.setGeometry(QtCore.QRect(10, 20, 141, 17))
        self.host_header_checkBox.setObjectName(_fromUtf8("host_header_checkBox"))
        self.host_header_lineEdit = QtGui.QLineEdit(self.groupBox_11)
        self.host_header_lineEdit.setGeometry(QtCore.QRect(150, 20, 201, 20))
        self.host_header_lineEdit.setObjectName(_fromUtf8("host_header_lineEdit"))
        self.headers_checkBox = QtGui.QCheckBox(self.groupBox_11)
        self.headers_checkBox.setGeometry(QtCore.QRect(370, 20, 101, 17))
        self.headers_checkBox.setObjectName(_fromUtf8("headers_checkBox"))
        self.headers_lineEdit = QtGui.QLineEdit(self.groupBox_11)
        self.headers_lineEdit.setGeometry(QtCore.QRect(470, 20, 301, 20))
        self.headers_lineEdit.setObjectName(_fromUtf8("headers_lineEdit"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_22)
        self.groupBox_9.setGeometry(QtCore.QRect(400, 80, 391, 51))
        self.groupBox_9.setCheckable(False)
        self.groupBox_9.setChecked(False)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.referer_checkBox = QtGui.QCheckBox(self.groupBox_9)
        self.referer_checkBox.setGeometry(QtCore.QRect(10, 20, 153, 17))
        self.referer_checkBox.setObjectName(_fromUtf8("referer_checkBox"))
        self.referer_lineEdit = QtGui.QLineEdit(self.groupBox_9)
        self.referer_lineEdit.setGeometry(QtCore.QRect(160, 20, 221, 20))
        self.referer_lineEdit.setObjectName(_fromUtf8("referer_lineEdit"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_22)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 781, 51))
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cookie_del_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.cookie_del_checkBox.setObjectName(_fromUtf8("cookie_del_checkBox"))
        self.gridLayout_3.addWidget(self.cookie_del_checkBox, 0, 2, 1, 1)
        self.cookie_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.cookie_checkBox.setObjectName(_fromUtf8("cookie_checkBox"))
        self.gridLayout_3.addWidget(self.cookie_checkBox, 0, 0, 1, 1)
        self.cookie_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.cookie_lineEdit.setObjectName(_fromUtf8("cookie_lineEdit"))
        self.gridLayout_3.addWidget(self.cookie_lineEdit, 0, 1, 1, 1)
        self.cookie_del_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.cookie_del_lineEdit.setObjectName(_fromUtf8("cookie_del_lineEdit"))
        self.gridLayout_3.addWidget(self.cookie_del_lineEdit, 0, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_22, _fromUtf8(""))
        self.tab_24 = QtGui.QWidget()
        self.tab_24.setObjectName(_fromUtf8("tab_24"))
        self.tamper_checkBox = QtGui.QCheckBox(self.tab_24)
        self.tamper_checkBox.setGeometry(QtCore.QRect(10, 20, 251, 17))
        self.tamper_checkBox.setObjectName(_fromUtf8("tamper_checkBox"))
        self.tamper_lineEdit = QtGui.QLineEdit(self.tab_24)
        self.tamper_lineEdit.setGeometry(QtCore.QRect(280, 20, 451, 20))
        self.tamper_lineEdit.setObjectName(_fromUtf8("tamper_lineEdit"))
        self.tamper_toolButton = QtGui.QToolButton(self.tab_24)
        self.tamper_toolButton.setGeometry(QtCore.QRect(740, 20, 25, 19))
        self.tamper_toolButton.setText(_fromUtf8(""))
        self.tamper_toolButton.setObjectName(_fromUtf8("tamper_toolButton"))
        self.tabWidget_2.addTab(self.tab_24, _fromUtf8(""))
        self.tab_18 = QtGui.QWidget()
        self.tab_18.setObjectName(_fromUtf8("tab_18"))
        self.crawl_checkBox = QtGui.QCheckBox(self.tab_18)
        self.crawl_checkBox.setGeometry(QtCore.QRect(10, 10, 261, 17))
        self.crawl_checkBox.setObjectName(_fromUtf8("crawl_checkBox"))
        self.crawl_spinBox = QtGui.QSpinBox(self.tab_18)
        self.crawl_spinBox.setGeometry(QtCore.QRect(290, 10, 42, 22))
        self.crawl_spinBox.setObjectName(_fromUtf8("crawl_spinBox"))
        self.crawl_exclude_checkBox = QtGui.QCheckBox(self.tab_18)
        self.crawl_exclude_checkBox.setGeometry(QtCore.QRect(340, 10, 211, 17))
        self.crawl_exclude_checkBox.setObjectName(_fromUtf8("crawl_exclude_checkBox"))
        self.crawl_exclude_lineEdit = QtGui.QLineEdit(self.tab_18)
        self.crawl_exclude_lineEdit.setGeometry(QtCore.QRect(552, 10, 211, 20))
        self.crawl_exclude_lineEdit.setObjectName(_fromUtf8("crawl_exclude_lineEdit"))
        self.forms_checkBox = QtGui.QCheckBox(self.tab_18)
        self.forms_checkBox.setGeometry(QtCore.QRect(10, 40, 201, 17))
        self.forms_checkBox.setObjectName(_fromUtf8("forms_checkBox"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_18)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 70, 771, 151))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 741, 123))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.code_radioButton = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.code_radioButton.setObjectName(_fromUtf8("code_radioButton"))
        self.gridLayout_5.addWidget(self.code_radioButton, 1, 1, 1, 1)
        self.not_string_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.not_string_lineEdit.setObjectName(_fromUtf8("not_string_lineEdit"))
        self.gridLayout_5.addWidget(self.not_string_lineEdit, 3, 2, 1, 1)
        self.not_string_radioButton = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.not_string_radioButton.setObjectName(_fromUtf8("not_string_radioButton"))
        self.gridLayout_5.addWidget(self.not_string_radioButton, 3, 1, 1, 1)
        self.regexp_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.regexp_lineEdit.setObjectName(_fromUtf8("regexp_lineEdit"))
        self.gridLayout_5.addWidget(self.regexp_lineEdit, 2, 2, 1, 1)
        self.regexp_radioButton = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.regexp_radioButton.setObjectName(_fromUtf8("regexp_radioButton"))
        self.gridLayout_5.addWidget(self.regexp_radioButton, 2, 1, 1, 1)
        self.string_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.string_lineEdit.setObjectName(_fromUtf8("string_lineEdit"))
        self.gridLayout_5.addWidget(self.string_lineEdit, 0, 2, 1, 1)
        self.string_radioButton = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.string_radioButton.setObjectName(_fromUtf8("string_radioButton"))
        self.gridLayout_5.addWidget(self.string_radioButton, 0, 1, 1, 1)
        self.code_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.code_lineEdit.setObjectName(_fromUtf8("code_lineEdit"))
        self.gridLayout_5.addWidget(self.code_lineEdit, 1, 2, 1, 1)
        self.titles_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.titles_checkBox.setObjectName(_fromUtf8("titles_checkBox"))
        self.gridLayout_5.addWidget(self.titles_checkBox, 4, 1, 1, 1)
        self.text_only_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.text_only_checkBox.setObjectName(_fromUtf8("text_only_checkBox"))
        self.gridLayout_5.addWidget(self.text_only_checkBox, 4, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_18, _fromUtf8(""))
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.groupBox = QtGui.QGroupBox(self.tab_17)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 751, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.enumeration_checkBox = QtGui.QCheckBox(self.groupBox)
        self.enumeration_checkBox.setAutoExclusive(True)
        self.enumeration_checkBox.setObjectName(_fromUtf8("enumeration_checkBox"))
        self.gridLayout.addWidget(self.enumeration_checkBox, 0, 0, 1, 1)
        self.file_system_access_checkBox = QtGui.QCheckBox(self.groupBox)
        self.file_system_access_checkBox.setAutoExclusive(True)
        self.file_system_access_checkBox.setObjectName(_fromUtf8("file_system_access_checkBox"))
        self.gridLayout.addWidget(self.file_system_access_checkBox, 0, 1, 1, 1)
        self.takeover_checkBox = QtGui.QCheckBox(self.groupBox)
        self.takeover_checkBox.setAutoExclusive(True)
        self.takeover_checkBox.setObjectName(_fromUtf8("takeover_checkBox"))
        self.gridLayout.addWidget(self.takeover_checkBox, 0, 2, 1, 1)
        self.UDFI_checkBox = QtGui.QCheckBox(self.groupBox)
        self.UDFI_checkBox.setAutoExclusive(True)
        self.UDFI_checkBox.setObjectName(_fromUtf8("UDFI_checkBox"))
        self.gridLayout.addWidget(self.UDFI_checkBox, 0, 3, 1, 1)
        self.custom_injection_checkBox = QtGui.QCheckBox(self.groupBox)
        self.custom_injection_checkBox.setAutoExclusive(True)
        self.custom_injection_checkBox.setObjectName(_fromUtf8("custom_injection_checkBox"))
        self.gridLayout.addWidget(self.custom_injection_checkBox, 0, 4, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_17)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 57, 791, 191))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox_5)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 771, 171))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 169))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(0, 0, 771, 171))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("sqlmap.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget_3.addTab(self.tab_17, _fromUtf8(""))

        self.retranslateUi(Detection)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Detection)

    def retranslateUi(self, Detection):
        Detection.setWindowTitle(_translate("Detection", "Web application Detection/Exploitation", None))
        self.detection_discard_pushButton.setText(_translate("Detection", "Discard", None))
        self.detection_save_pushButton.setText(_translate("Detection", "Save", None))
        self.url_label.setText(_translate("Detection", "Target URL", None))
        self.output_groupBox.setTitle(_translate("Detection", "Output", None))
        self.output_dir_lineEdit.setText(_translate("Detection", "sqlmap/output", None))
        self.output_dir_checkBox.setText(_translate("Detection", "Custom output directory path", None))
#        self.URI_checkBox.setText(_translate("Detection", "URI injection point", None))
        self.textBrowser_2.setHtml(_translate("Detection", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:8pt; color:#444444; background-color:#ffffff;\">There are special cases when injection point is within the URI itself. sqlmap does not perform any automatic test against URI paths, unless manually pointed to. You have to specify these injection points in the command line by appending an asterisk (*) </span></p></body></html>", None))
        self.eval_checkBox.setText(_translate("Detection", "Evaluate provided Python code before the request", None))
        self.label_2.setText(_translate("Detection", "URI injection point", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_19), _translate("Detection", "GET Parameters", None))
        self.data_radioButton.setText(_translate("Detection", "Enter POST parameters (--data)", None))
        self.testparameter_checkBox.setText(_translate("Detection", "Testable parameter(s)(--p)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_20), _translate("Detection", "POST parameters", None))
        self.requestfile_checkBox.setText(_translate("Detection", "Load HTTP request from a file", None))
        self.testparam_checkBox.setText(_translate("Detection", "Testable parameter(s)(--p)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Detection", "HTTP POST REQUEST FILE", None))
        self.groupBox_10.setTitle(_translate("Detection", "HTTP User-Agent header", None))
        self.user_agent_checkBox.setText(_translate("Detection", "HTTP User-Agent header value", None))
        self.groupBox_11.setTitle(_translate("Detection", "Headers", None))
        self.host_header_checkBox.setText(_translate("Detection", "HTTP Host header value", None))
        self.headers_checkBox.setText(_translate("Detection", "Extra headers", None))
        self.groupBox_9.setTitle(_translate("Detection", " HTTP Referer header", None))
        self.referer_checkBox.setText(_translate("Detection", "HTTP Referer header value", None))
        self.groupBox_2.setTitle(_translate("Detection", "HTTP Cookie header ", None))
        self.cookie_del_checkBox.setText(_translate("Detection", "splitting cookie values", None))
        self.cookie_checkBox.setText(_translate("Detection", "HTTP Cookie header value", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_22), _translate("Detection", "HTTP Headers", None))
        self.tamper_checkBox.setText(_translate("Detection", "Use given script(s) for tampering injection data", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_24), _translate("Detection", "Tampering", None))
        self.crawl_checkBox.setText(_translate("Detection", " Crawl the website starting from the target URL", None))
        self.crawl_exclude_checkBox.setText(_translate("Detection", "Regexp to exclude pages from crawling", None))
        self.forms_checkBox.setText(_translate("Detection", "Parse and test forms on target URL", None))
        self.groupBox_4.setTitle(_translate("Detection", "Customize the detection phase", None))
        self.code_radioButton.setText(_translate("Detection", "HTTP code to match when query is evaluated to True", None))
        self.not_string_radioButton.setText(_translate("Detection", "String to match when query is evaluated to False", None))
        self.regexp_radioButton.setText(_translate("Detection", "Regexp to match when query is evaluated to True", None))
        self.string_radioButton.setText(_translate("Detection", "String to match when query is evaluated to True", None))
        self.titles_checkBox.setText(_translate("Detection", "Compare pages based only on their titles", None))
        self.text_only_checkBox.setText(_translate("Detection", "Compare pages based only on  textual content", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_18), _translate("Detection", "General", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("Detection", "Detection", None))
        self.groupBox.setTitle(_translate("Detection", "Exploitation options", None))
        self.enumeration_checkBox.setText(_translate("Detection", "Enumeration", None))
        self.file_system_access_checkBox.setText(_translate("Detection", "File System Access", None))
        self.takeover_checkBox.setText(_translate("Detection", "Takeover", None))
        self.UDFI_checkBox.setText(_translate("Detection", "UDFI", None))
        self.custom_injection_checkBox.setText(_translate("Detection", "Custom injection payload", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_17), _translate("Detection", "Exploitation", None))

