# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'direct_old.ui'
#
# Created: Mon Jul 03 00:04:09 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormDirect(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        #Form.resize(838, 420)
	Form.resize(QtCore.QSize(QtCore.QRect(0,0,838, 420).size()).expandedTo(Form.minimumSizeHint()))

        self.direct_conn_groupBox = QtGui.QGroupBox(Form)
        self.direct_conn_groupBox.setGeometry(QtCore.QRect(10, 10, 821, 81))
        self.direct_conn_groupBox.setObjectName(_fromUtf8("direct_conn_groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.direct_conn_groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 801, 71))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(4, 3, 5, 3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 10, 1, 1)
        self.username_radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.username_radioButton.setText(_fromUtf8(""))
        self.username_radioButton.setObjectName(_fromUtf8("username_radioButton"))
        self.gridLayout.addWidget(self.username_radioButton, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.port_spinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.port_spinBox.setMaximum(9999)
        self.port_spinBox.setObjectName(_fromUtf8("port_spinBox"))
        self.gridLayout.addWidget(self.port_spinBox, 0, 9, 1, 1)
        self.username_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.username_lineEdit.setObjectName(_fromUtf8("username_lineEdit"))
        self.gridLayout.addWidget(self.username_lineEdit, 0, 2, 1, 2)
        self.IP_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.IP_lineEdit.setProperty("lista", [])
        self.IP_lineEdit.setObjectName(_fromUtf8("IP_lineEdit"))
        self.gridLayout.addWidget(self.IP_lineEdit, 0, 7, 1, 1)
        self.db_name_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.db_name_lineEdit.setObjectName(_fromUtf8("db_name_lineEdit"))
        self.gridLayout.addWidget(self.db_name_lineEdit, 0, 11, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 8, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 1)
        self.password_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.password_lineEdit.setObjectName(_fromUtf8("password_lineEdit"))
        self.gridLayout.addWidget(self.password_lineEdit, 0, 5, 1, 1)
        self.db_filepath_radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.db_filepath_radioButton.setText(_fromUtf8(""))
        self.db_filepath_radioButton.setObjectName(_fromUtf8("db_filepath_radioButton"))
        self.gridLayout.addWidget(self.db_filepath_radioButton, 1, 0, 1, 1)
        self.db_filepath_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.db_filepath_lineEdit.setObjectName(_fromUtf8("db_filepath_lineEdit"))
        self.gridLayout.addWidget(self.db_filepath_lineEdit, 1, 2, 1, 8)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 821, 221))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 801, 201))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 799, 199))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(5, 0, 791, 201))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("sqlmap.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.direct_save_pushButton = QtGui.QPushButton(Form)
        self.direct_save_pushButton.setGeometry(QtCore.QRect(570, 390, 75, 23))
        self.direct_save_pushButton.setObjectName(_fromUtf8("direct_save_pushButton"))
        self.direct_discard_pushButton = QtGui.QPushButton(Form)
        self.direct_discard_pushButton.setGeometry(QtCore.QRect(650, 390, 75, 23))
        self.direct_discard_pushButton.setObjectName(_fromUtf8("direct_discard_pushButton"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 821, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.oracle_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.oracle_toolButton.setGeometry(QtCore.QRect(494, 16, 71, 19))
        self.oracle_toolButton.setObjectName(_fromUtf8("oracle_toolButton"))
        self.mysql_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.mysql_toolButton.setGeometry(QtCore.QRect(414, 16, 71, 20))
        self.mysql_toolButton.setObjectName(_fromUtf8("mysql_toolButton"))
        self.sybase_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.sybase_toolButton.setGeometry(QtCore.QRect(740, 14, 71, 20))
        self.sybase_toolButton.setObjectName(_fromUtf8("sybase_toolButton"))
        self.postgresql_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.postgresql_toolButton.setGeometry(QtCore.QRect(573, 16, 71, 20))
        self.postgresql_toolButton.setObjectName(_fromUtf8("postgresql_toolButton"))
        self.hsqldb_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.hsqldb_toolButton.setGeometry(QtCore.QRect(248, 15, 71, 20))
        self.hsqldb_toolButton.setObjectName(_fromUtf8("hsqldb_toolButton"))
        self.mssqlserver_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.mssqlserver_toolButton.setGeometry(QtCore.QRect(330, 16, 71, 20))
        self.mssqlserver_toolButton.setObjectName(_fromUtf8("mssqlserver_toolButton"))
        self.sqlite_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.sqlite_toolButton.setGeometry(QtCore.QRect(658, 16, 71, 20))
        self.sqlite_toolButton.setObjectName(_fromUtf8("sqlite_toolButton"))
        self.firebird_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.firebird_toolButton.setGeometry(QtCore.QRect(170, 15, 71, 20))
        self.firebird_toolButton.setObjectName(_fromUtf8("firebird_toolButton"))
        self.access_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.access_toolButton.setGeometry(QtCore.QRect(9, 16, 71, 20))
        self.access_toolButton.setObjectName(_fromUtf8("access_toolButton"))
        self.db2_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.db2_toolButton.setGeometry(QtCore.QRect(90, 16, 71, 20))
        self.db2_toolButton.setObjectName(_fromUtf8("db2_toolButton"))
        self.actionShowEnumeration = QtGui.QAction(Form)
        self.actionShowEnumeration.setObjectName(_fromUtf8("actionShowEnumeration"))
        self.actionHide_direct_mdi = QtGui.QAction(Form)
        self.actionHide_direct_mdi.setObjectName(_fromUtf8("actionHide_direct_mdi"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.db_filepath_radioButton, QtCore.SIGNAL(_fromUtf8("pressed()")), self.username_lineEdit.clear)
        QtCore.QObject.connect(self.username_radioButton, QtCore.SIGNAL(_fromUtf8("pressed()")), self.db_filepath_lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Direct", None))
        self.direct_conn_groupBox.setTitle(_translate("Form", "DB connection ", None))
        self.label_5.setText(_translate("Form", "DB name", None))
        self.label.setText(_translate("Form", "Username", None))
        self.label_3.setText(_translate("Form", "IP", None))
        self.label_4.setText(_translate("Form", "Port", None))
        self.label_2.setText(_translate("Form", "Password", None))
        self.label_7.setText(_translate("Form", "DB_FILEPATH", None))
        self.direct_save_pushButton.setText(_translate("Form", "Save", None))
        self.direct_discard_pushButton.setText(_translate("Form", "Discard", None))
        self.groupBox_2.setTitle(_translate("Form", "Exploitation", None))
        self.oracle_toolButton.setText(_translate("Form", "Oracle", None))
        self.mysql_toolButton.setText(_translate("Form", "MySql", None))
        self.sybase_toolButton.setText(_translate("Form", "Sybase", None))
        self.postgresql_toolButton.setText(_translate("Form", "PostgreSql", None))
        self.hsqldb_toolButton.setText(_translate("Form", "HsqlDB", None))
        self.mssqlserver_toolButton.setText(_translate("Form", "MsSqlServer", None))
        self.sqlite_toolButton.setText(_translate("Form", "Sqlite", None))
        self.firebird_toolButton.setText(_translate("Form", "Firebird", None))
        self.access_toolButton.setText(_translate("Form", "Access", None))
        self.db2_toolButton.setText(_translate("Form", "DB2", None))
        self.actionShowEnumeration.setText(_translate("Form", "showEnumeration", None))
        self.actionHide_direct_mdi.setText(_translate("Form", "hide direct mdi", None))

