# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firebird.ui'
#
# Created: Mon Oct 10 04:16:17 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormFirebird(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(899, 656)
        self.tabWidget_4 = QtGui.QTabWidget(Form)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 781, 151))
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.db2_enum_tab_2 = QtGui.QWidget()
        self.db2_enum_tab_2.setObjectName(_fromUtf8("db2_enum_tab_2"))
        self.tabWidget_5 = QtGui.QTabWidget(self.db2_enum_tab_2)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 771, 121))
        self.tabWidget_5.setObjectName(_fromUtf8("tabWidget_5"))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.gridLayoutWidget_9 = QtGui.QWidget(self.tab_11)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 711, 81))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.firebird_roles_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_9)
        self.firebird_roles_checkBox.setObjectName(_fromUtf8("firebird_roles_checkBox"))
        self.gridLayout_9.addWidget(self.firebird_roles_checkBox, 0, 1, 1, 1)
        self.firebird_is_dba_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_9)
        self.firebird_is_dba_checkBox.setObjectName(_fromUtf8("firebird_is_dba_checkBox"))
        self.gridLayout_9.addWidget(self.firebird_is_dba_checkBox, 1, 1, 1, 1)
        self.firebird_current_user_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_9)
        self.firebird_current_user_checkBox.setObjectName(_fromUtf8("firebird_current_user_checkBox"))
        self.gridLayout_9.addWidget(self.firebird_current_user_checkBox, 0, 0, 1, 1)
        self.firebird_users_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_9)
        self.firebird_users_checkBox.setObjectName(_fromUtf8("firebird_users_checkBox"))
        self.gridLayout_9.addWidget(self.firebird_users_checkBox, 2, 0, 1, 1)
        self.firebird_privileges_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_9)
        self.firebird_privileges_checkBox.setObjectName(_fromUtf8("firebird_privileges_checkBox"))
        self.gridLayout_9.addWidget(self.firebird_privileges_checkBox, 1, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_11, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.gridLayoutWidget_10 = QtGui.QWidget(self.tab_12)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(20, 10, 701, 61))
        self.gridLayoutWidget_10.setObjectName(_fromUtf8("gridLayoutWidget_10"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.firebird_columns_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_10)
        self.firebird_columns_checkBox.setObjectName(_fromUtf8("firebird_columns_checkBox"))
        self.gridLayout_10.addWidget(self.firebird_columns_checkBox, 1, 0, 1, 1)
        self.firebird_count_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_10)
        self.firebird_count_checkBox.setObjectName(_fromUtf8("firebird_count_checkBox"))
        self.gridLayout_10.addWidget(self.firebird_count_checkBox, 0, 0, 1, 1)
        self.firebird_schema_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_10)
        self.firebird_schema_checkBox.setObjectName(_fromUtf8("firebird_schema_checkBox"))
        self.gridLayout_10.addWidget(self.firebird_schema_checkBox, 0, 1, 1, 1)
        self.firebird_tables_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_10)
        self.firebird_tables_checkBox.setObjectName(_fromUtf8("firebird_tables_checkBox"))
        self.gridLayout_10.addWidget(self.firebird_tables_checkBox, 1, 1, 1, 1)
        self.tabWidget_5.addTab(self.tab_12, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.tab_13)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 222, 61))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.firebird_dump_all_checkBox = QtGui.QCheckBox(self.formLayoutWidget_4)
        self.firebird_dump_all_checkBox.setAutoExclusive(True)
        self.firebird_dump_all_checkBox.setObjectName(_fromUtf8("firebird_dump_all_checkBox"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.firebird_dump_all_checkBox)
        self.firebird_dump_checkBox = QtGui.QCheckBox(self.formLayoutWidget_4)
        self.firebird_dump_checkBox.setAutoExclusive(True)
        self.firebird_dump_checkBox.setObjectName(_fromUtf8("firebird_dump_checkBox"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.firebird_dump_checkBox)
        self.tabWidget_5.addTab(self.tab_13, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.tab_15)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.firebird_banner_checkBox = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.firebird_banner_checkBox.setObjectName(_fromUtf8("firebird_banner_checkBox"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.firebird_banner_checkBox)
        self.tabWidget_5.addTab(self.tab_15, _fromUtf8(""))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.firebird_sql_query_checkBox = QtGui.QCheckBox(self.tab_16)
        self.firebird_sql_query_checkBox.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.firebird_sql_query_checkBox.setObjectName(_fromUtf8("firebird_sql_query_checkBox"))
        self.firebird_sql_query_lineEdit = QtGui.QLineEdit(self.tab_16)
        self.firebird_sql_query_lineEdit.setGeometry(QtCore.QRect(230, 10, 491, 20))
        self.firebird_sql_query_lineEdit.setObjectName(_fromUtf8("firebird_sql_query_lineEdit"))
        self.firebird_sqlshell_checkBox = QtGui.QCheckBox(self.tab_16)
        self.firebird_sqlshell_checkBox.setGeometry(QtCore.QRect(10, 40, 201, 17))
        self.firebird_sqlshell_checkBox.setObjectName(_fromUtf8("firebird_sqlshell_checkBox"))
        self.firebird_sqlfile_checkBox = QtGui.QCheckBox(self.tab_16)
        self.firebird_sqlfile_checkBox.setGeometry(QtCore.QRect(10, 70, 221, 17))
        self.firebird_sqlfile_checkBox.setObjectName(_fromUtf8("firebird_sqlfile_checkBox"))
        self.firebird_sqlfile_lineEdit = QtGui.QLineEdit(self.tab_16)
        self.firebird_sqlfile_lineEdit.setGeometry(QtCore.QRect(232, 70, 491, 20))
        self.firebird_sqlfile_lineEdit.setObjectName(_fromUtf8("firebird_sqlfile_lineEdit"))
        self.tabWidget_5.addTab(self.tab_16, _fromUtf8(""))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.firebird_brute_tables_checkBox = QtGui.QCheckBox(self.tab_17)
        self.firebird_brute_tables_checkBox.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.firebird_brute_tables_checkBox.setObjectName(_fromUtf8("firebird_brute_tables_checkBox"))
        self.brute_columns_checkBox_3 = QtGui.QCheckBox(self.tab_17)
        self.brute_columns_checkBox_3.setGeometry(QtCore.QRect(20, 100, 151, 17))
        self.brute_columns_checkBox_3.setObjectName(_fromUtf8("brute_columns_checkBox_3"))
        self.firebird_brute_columns_checkBox = QtGui.QCheckBox(self.tab_17)
        self.firebird_brute_columns_checkBox.setGeometry(QtCore.QRect(10, 40, 151, 17))
        self.firebird_brute_columns_checkBox.setObjectName(_fromUtf8("firebird_brute_columns_checkBox"))
        self.tabWidget_5.addTab(self.tab_17, _fromUtf8(""))
        self.tabWidget_4.addTab(self.db2_enum_tab_2, _fromUtf8(""))
        self.db2_fingerprint_tab_2 = QtGui.QWidget()
        self.db2_fingerprint_tab_2.setObjectName(_fromUtf8("db2_fingerprint_tab_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.db2_fingerprint_tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(9, 10, 751, 80))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.firebird__fingerprint_checkBox = QtGui.QCheckBox(self.groupBox_5)
        self.firebird__fingerprint_checkBox.setGeometry(QtCore.QRect(10, 30, 281, 17))
        self.firebird__fingerprint_checkBox.setObjectName(_fromUtf8("firebird__fingerprint_checkBox"))
        self.tabWidget_4.addTab(self.db2_fingerprint_tab_2, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.firebird_roles_checkBox.setText(_translate("Form", "Enumerate DBMS users roles", None))
        self.firebird_is_dba_checkBox.setText(_translate("Form", "Detect if  current user is DBA", None))
        self.firebird_current_user_checkBox.setText(_translate("Form", "Retrieve DBMS current user", None))
        self.firebird_users_checkBox.setText(_translate("Form", "Enumerate DBMS users", None))
        self.firebird_privileges_checkBox.setText(_translate("Form", "Enumerate DBMS users privileges", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_11), _translate("Form", "Users", None))
        self.firebird_columns_checkBox.setText(_translate("Form", "Enumerate DBMS database table columns", None))
        self.firebird_count_checkBox.setText(_translate("Form", "Retrieve number of entries for table(s)", None))
        self.firebird_schema_checkBox.setText(_translate("Form", "Enumerate DBMS schema", None))
        self.firebird_tables_checkBox.setText(_translate("Form", "Enumerate DBMS database tables", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_12), _translate("Form", "Databases", None))
        self.firebird_dump_all_checkBox.setText(_translate("Form", "Dump all DBMS databases tables entries", None))
        self.firebird_dump_checkBox.setText(_translate("Form", "Dump DBMS database table entries", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_13), _translate("Form", "Entries", None))
        self.firebird_banner_checkBox.setText(_translate("Form", "Retrieve DBMS banner", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_15), _translate("Form", "Generic", None))
        self.firebird_sql_query_checkBox.setText(_translate("Form", "SQL statement to be executed", None))
        self.firebird_sqlshell_checkBox.setText(_translate("Form", "Prompt for an interactive SQL shell", None))
        self.firebird_sqlfile_checkBox.setText(_translate("Form", "Execute SQL statements from given file", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_16), _translate("Form", "Custom", None))
        self.firebird_brute_tables_checkBox.setText(_translate("Form", "Check of common tables", None))
        self.brute_columns_checkBox_3.setText(_translate("Form", "Check  of common columns", None))
        self.firebird_brute_columns_checkBox.setText(_translate("Form", "Check  of common columns", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_17), _translate("Form", "Brute force", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.db2_enum_tab_2), _translate("Form", "Enumeration", None))
        self.firebird__fingerprint_checkBox.setText(_translate("Form", "Extensive database management system fingerprint", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.db2_fingerprint_tab_2), _translate("Form", "Fingerprint", None))

