# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Jun 30 01:59:32 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(899, 656)
		
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 891, 591))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.scan_tab = QtGui.QWidget()
        self.scan_tab.setObjectName(_fromUtf8("scan_tab"))
        self.groupBox = QtGui.QGroupBox(self.scan_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 861, 51))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 851, 41))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.run_pushButton = QtGui.QPushButton(self.formLayoutWidget)
        self.run_pushButton.setAutoExclusive(True)
        self.run_pushButton.setFlat(False)
        self.run_pushButton.setObjectName(_fromUtf8("run_pushButton"))
        self.gridLayout.addWidget(self.run_pushButton, 0, 2, 1, 1)
        self.command_lineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.command_lineEdit.setObjectName(_fromUtf8("command_lineEdit"))
        self.gridLayout.addWidget(self.command_lineEdit, 0, 1, 1, 1)
        self.stop_pushButton = QtGui.QPushButton(self.formLayoutWidget)
        self.stop_pushButton.setAutoExclusive(True)
        self.stop_pushButton.setObjectName(_fromUtf8("stop_pushButton"))
        self.gridLayout.addWidget(self.stop_pushButton, 0, 3, 1, 1)
        self.scan_tabWidget = QtGui.QTabWidget(self.scan_tab)
        self.scan_tabWidget.setGeometry(QtCore.QRect(10, 80, 861, 481))
        self.scan_tabWidget.setObjectName(_fromUtf8("scan_tabWidget"))
        self.direct_tab = QtGui.QWidget()
        self.direct_tab.setObjectName(_fromUtf8("direct_tab"))
        self.scan_tabWidget.addTab(self.direct_tab, _fromUtf8(""))
        self.detection_tab = QtGui.QWidget()
        self.detection_tab.setObjectName(_fromUtf8("detection_tab"))
        self.scan_tabWidget.addTab(self.detection_tab, _fromUtf8(""))
        self.tabWidget.addTab(self.scan_tab, _fromUtf8(""))
        self.output_tab = QtGui.QWidget()
        self.output_tab.setObjectName(_fromUtf8("output_tab"))
        self.tabWidget_output = QtGui.QTabWidget(self.output_tab)
        self.tabWidget_output.setGeometry(QtCore.QRect(0, 0, 781, 511))
        self.tabWidget_output.setBaseSize(QtCore.QSize(2, 3))
        self.tabWidget_output.setObjectName(_fromUtf8("tabWidget_output"))
        self.csv_output = QtGui.QWidget()
        self.csv_output.setObjectName(_fromUtf8("csv_output"))
        self.csv_plainTextEdit = QtGui.QPlainTextEdit(self.csv_output)
        self.csv_plainTextEdit.setGeometry(QtCore.QRect(13, 10, 741, 461))
        self.csv_plainTextEdit.setBackgroundVisible(False)
        self.csv_plainTextEdit.setCenterOnScroll(False)
        self.csv_plainTextEdit.setObjectName(_fromUtf8("csv_plainTextEdit"))
        self.tabWidget_output.addTab(self.csv_output, _fromUtf8(""))
        self.html_output = QtGui.QWidget()
        self.html_output.setObjectName(_fromUtf8("html_output"))
        self.html_plainTextEdit = QtGui.QPlainTextEdit(self.html_output)
        self.html_plainTextEdit.setGeometry(QtCore.QRect(10, 10, 751, 461))
        self.html_plainTextEdit.setObjectName(_fromUtf8("html_plainTextEdit"))
        self.tabWidget_output.addTab(self.html_output, _fromUtf8(""))
        self.sqlite_output = QtGui.QWidget()
        self.sqlite_output.setObjectName(_fromUtf8("sqlite_output"))
        self.sqlite_plainTextEdit = QtGui.QPlainTextEdit(self.sqlite_output)
        self.sqlite_plainTextEdit.setGeometry(QtCore.QRect(10, 10, 751, 461))
        self.sqlite_plainTextEdit.setObjectName(_fromUtf8("sqlite_plainTextEdit"))
        self.tabWidget_output.addTab(self.sqlite_output, _fromUtf8(""))
        self.log_output = QtGui.QWidget()
        self.log_output.setObjectName(_fromUtf8("log_output"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.log_output)
        self.plainTextEdit.setGeometry(QtCore.QRect(3, 10, 751, 461))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.tabWidget_output.addTab(self.log_output, _fromUtf8(""))
        self.error = QtGui.QWidget()
        self.error.setObjectName(_fromUtf8("error"))
        self.error_plainTextEdit = QtGui.QPlainTextEdit(self.error)
        self.error_plainTextEdit.setGeometry(QtCore.QRect(10, 10, 751, 461))
        self.error_plainTextEdit.setObjectName(_fromUtf8("error_plainTextEdit"))
        self.tabWidget_output.addTab(self.error, _fromUtf8(""))
        self.tabWidget.addTab(self.output_tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
#        self.menuUsers = QtGui.QMenu(self.menubar)
#        self.menuUsers.setObjectName(_fromUtf8("menuUsers"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCheck_dependencies = QtGui.QAction(MainWindow)
        self.actionCheck_dependencies.setObjectName(_fromUtf8("actionCheck_dependencies"))
        self.actionLoad_options = QtGui.QAction(MainWindow)
        self.actionLoad_options.setObjectName(_fromUtf8("actionLoad_options"))
        self.actionOpen_log = QtGui.QAction(MainWindow)
        self.actionOpen_log.setObjectName(_fromUtf8("actionOpen_log"))
        self.actionOpen_log_2 = QtGui.QAction(MainWindow)
        self.actionOpen_log_2.setObjectName(_fromUtf8("actionOpen_log_2"))
        self.actionSave_options = QtGui.QAction(MainWindow)
        self.actionSave_options.setObjectName(_fromUtf8("actionSave_options"))
        self.actionLoad_options = QtGui.QAction(MainWindow)
        self.actionLoad_options.setObjectName(_fromUtf8("actionLoad_options"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDirect_connection = QtGui.QAction(MainWindow)
        self.actionDirect_connection.setObjectName(_fromUtf8("actionDirect_connection"))
        self.actionShow_advanced_help_message = QtGui.QAction(MainWindow)
        self.actionShow_advanced_help_message.setObjectName(_fromUtf8("actionShow_advanced_help_message"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionDetection_Exploitation = QtGui.QAction(MainWindow)
        self.actionDetection_Exploitation.setObjectName(_fromUtf8("actionDetection_Exploitation"))
#        self.actionSimple_wizard_interface_for_beginner_users = QtGui.QAction(MainWindow)
 #       self.actionSimple_wizard_interface_for_beginner_users.setObjectName(_fromUtf8("actionSimple_wizard_interface_for_beginner_users"))
        self.menuFile.addAction(self.actionOpen_log_2)
        self.menuFile.addAction(self.actionSave_options)
        self.menuFile.addAction(self.actionLoad_options)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionShow_advanced_help_message)
#       self.menuUsers.addAction(self.actionDirect_connection)
 #       self.menuUsers.addAction(self.actionDetection_Exploitation)
        self.menubar.addAction(self.menuFile.menuAction())
 #       self.menubar.addAction(self.menuUsers.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLoad_options)
        self.toolBar.addAction(self.actionOpen_log)
  #      self.toolBar.addAction(self.actionSimple_wizard_interface_for_beginner_users)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.scan_tabWidget.setCurrentIndex(0)
        self.tabWidget_output.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SqlMap GUI", None))
        self.label.setText(_translate("MainWindow", "Command", None))
        self.run_pushButton.setText(_translate("MainWindow", "Run", None))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop", None))
        self.scan_tabWidget.setTabText(self.scan_tabWidget.indexOf(self.direct_tab), _translate("MainWindow", "Direct", None))
        self.scan_tabWidget.setTabText(self.scan_tabWidget.indexOf(self.detection_tab), _translate("MainWindow", "Detection/Exploitation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scan_tab), _translate("MainWindow", "Scan", None))
        self.csv_output.setToolTip(_translate("MainWindow", "<html><head/><body><p></p></body></html>", None))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.csv_output), _translate("MainWindow", "CSV Format", None))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.html_output), _translate("MainWindow", "HTML Format", None))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.sqlite_output), _translate("MainWindow", "SQLITE Format", None))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.log_output), _translate("MainWindow", "All Logs ", None))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.error), _translate("MainWindow", "Error", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_tab), _translate("MainWindow", "Output", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
 #       self.menuUsers.setTitle(_translate("MainWindow", "Users", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionCheck_dependencies.setText(_translate("MainWindow", "Check dependencies", None))
        self.actionCheck_dependencies.setToolTip(_translate("MainWindow", "Check for missing (non-core) sqlmap dependencies", None))
        self.actionLoad_options.setText(_translate("MainWindow", "Load options from a file  ", None))
        self.actionLoad_options.setToolTip(_translate("MainWindow", "Load options from a file ", None))
        self.actionOpen_log.setText(_translate("MainWindow", "Open log", None))
        self.actionOpen_log.setToolTip(_translate("MainWindow", "Open log", None))
        self.actionOpen_log_2.setText(_translate("MainWindow", "Open log", None))
        self.actionSave_options.setText(_translate("MainWindow", "Save options to a file", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionDirect_connection.setText(_translate("MainWindow", "Direct connection", None))
        self.actionShow_advanced_help_message.setText(_translate("MainWindow", "advanced help message", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionDetection_Exploitation.setText(_translate("MainWindow", "Detection/Exploitation", None))
   #     self.actionSimple_wizard_interface_for_beginner_users.setText(_translate("MainWindow", "Simple wizard interface for beginner users", None))

