# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mssqlenum.ui'
#
# Created: Mon Oct 10 15:01:30 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormMssEnum(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(899, 656)
        self.tabWidget_17 = QtGui.QTabWidget(Form)
        self.tabWidget_17.setGeometry(QtCore.QRect(0, 0, 771, 121))
        self.tabWidget_17.setObjectName(_fromUtf8("tabWidget_17"))
        self.tab_65 = QtGui.QWidget()
        self.tab_65.setObjectName(_fromUtf8("tab_65"))
        self.gridLayoutWidget_27 = QtGui.QWidget(self.tab_65)
        self.gridLayoutWidget_27.setGeometry(QtCore.QRect(10, 10, 741, 61))
        self.gridLayoutWidget_27.setObjectName(_fromUtf8("gridLayoutWidget_27"))
        self.gridLayout_27 = QtGui.QGridLayout(self.gridLayoutWidget_27)
        self.gridLayout_27.setMargin(0)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.mssql_current_user_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_27)
        self.mssql_current_user_checkBox.setObjectName(_fromUtf8("mssql_current_user_checkBox"))
        self.gridLayout_27.addWidget(self.mssql_current_user_checkBox, 0, 0, 1, 1)
        self.mssql_passwords_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_27)
        self.mssql_passwords_checkBox.setObjectName(_fromUtf8("mssql_passwords_checkBox"))
        self.gridLayout_27.addWidget(self.mssql_passwords_checkBox, 1, 0, 1, 1)
        self.mssql_privileges_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_27)
        self.mssql_privileges_checkBox.setObjectName(_fromUtf8("mssql_privileges_checkBox"))
        self.gridLayout_27.addWidget(self.mssql_privileges_checkBox, 1, 1, 1, 1)
        self.mssql_roles_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_27)
        self.mssql_roles_checkBox.setObjectName(_fromUtf8("mssql_roles_checkBox"))
        self.gridLayout_27.addWidget(self.mssql_roles_checkBox, 0, 1, 1, 1)
        self.mssql_users_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_27)
        self.mssql_users_checkBox.setObjectName(_fromUtf8("mssql_users_checkBox"))
        self.gridLayout_27.addWidget(self.mssql_users_checkBox, 0, 2, 1, 1)
        self.mssql_is_dba_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_27)
        self.mssql_is_dba_checkBox.setObjectName(_fromUtf8("mssql_is_dba_checkBox"))
        self.gridLayout_27.addWidget(self.mssql_is_dba_checkBox, 1, 2, 1, 1)
        self.tabWidget_17.addTab(self.tab_65, _fromUtf8(""))
        self.tab_66 = QtGui.QWidget()
        self.tab_66.setObjectName(_fromUtf8("tab_66"))
        self.gridLayoutWidget_28 = QtGui.QWidget(self.tab_66)
        self.gridLayoutWidget_28.setGeometry(QtCore.QRect(20, 10, 741, 61))
        self.gridLayoutWidget_28.setObjectName(_fromUtf8("gridLayoutWidget_28"))
        self.gridLayout_28 = QtGui.QGridLayout(self.gridLayoutWidget_28)
        self.gridLayout_28.setMargin(0)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.mssql_schema_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_28)
        self.mssql_schema_checkBox.setObjectName(_fromUtf8("mssql_schema_checkBox"))
        self.gridLayout_28.addWidget(self.mssql_schema_checkBox, 0, 1, 1, 1)
        self.mssql_columns_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_28)
        self.mssql_columns_checkBox.setObjectName(_fromUtf8("mssql_columns_checkBox"))
        self.gridLayout_28.addWidget(self.mssql_columns_checkBox, 1, 0, 1, 1)
        self.mssql_count_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_28)
        self.mssql_count_checkBox.setObjectName(_fromUtf8("mssql_count_checkBox"))
        self.gridLayout_28.addWidget(self.mssql_count_checkBox, 0, 0, 1, 1)
        self.mssql_dbs_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_28)
        self.mssql_dbs_checkBox.setObjectName(_fromUtf8("mssql_dbs_checkBox"))
        self.gridLayout_28.addWidget(self.mssql_dbs_checkBox, 0, 2, 1, 1)
        self.mssql_tables_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_28)
        self.mssql_tables_checkBox.setObjectName(_fromUtf8("mssql_tables_checkBox"))
        self.gridLayout_28.addWidget(self.mssql_tables_checkBox, 1, 1, 1, 1)
        self.tabWidget_17.addTab(self.tab_66, _fromUtf8(""))
        self.tab_67 = QtGui.QWidget()
        self.tab_67.setObjectName(_fromUtf8("tab_67"))
        self.formLayoutWidget_19 = QtGui.QWidget(self.tab_67)
        self.formLayoutWidget_19.setGeometry(QtCore.QRect(10, 10, 222, 61))
        self.formLayoutWidget_19.setObjectName(_fromUtf8("formLayoutWidget_19"))
        self.formLayout_19 = QtGui.QFormLayout(self.formLayoutWidget_19)
        self.formLayout_19.setMargin(0)
        self.formLayout_19.setObjectName(_fromUtf8("formLayout_19"))
        self.mssql_dump_all_checkBox = QtGui.QCheckBox(self.formLayoutWidget_19)
        self.mssql_dump_all_checkBox.setAutoExclusive(True)
        self.mssql_dump_all_checkBox.setObjectName(_fromUtf8("mssql_dump_all_checkBox"))
        self.formLayout_19.setWidget(2, QtGui.QFormLayout.LabelRole, self.mssql_dump_all_checkBox)
        self.mssql_dump_checkBox = QtGui.QCheckBox(self.formLayoutWidget_19)
        self.mssql_dump_checkBox.setAutoExclusive(True)
        self.mssql_dump_checkBox.setObjectName(_fromUtf8("mssql_dump_checkBox"))
        self.formLayout_19.setWidget(1, QtGui.QFormLayout.LabelRole, self.mssql_dump_checkBox)
        self.tabWidget_17.addTab(self.tab_67, _fromUtf8(""))
        self.tab_68 = QtGui.QWidget()
        self.tab_68.setObjectName(_fromUtf8("tab_68"))
        self.mssql_search_checkBox = QtGui.QCheckBox(self.tab_68)
        self.mssql_search_checkBox.setGeometry(QtCore.QRect(20, 10, 274, 17))
        self.mssql_search_checkBox.setObjectName(_fromUtf8("mssql_search_checkBox"))
        self.gridLayoutWidget_29 = QtGui.QWidget(self.tab_68)
        self.gridLayoutWidget_29.setGeometry(QtCore.QRect(20, 30, 741, 51))
        self.gridLayoutWidget_29.setObjectName(_fromUtf8("gridLayoutWidget_29"))
        self.gridLayout_29 = QtGui.QGridLayout(self.gridLayoutWidget_29)
        self.gridLayout_29.setMargin(0)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.mssql_DB_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_29)
        self.mssql_DB_lineEdit.setObjectName(_fromUtf8("mssql_DB_lineEdit"))
        self.gridLayout_29.addWidget(self.mssql_DB_lineEdit, 0, 1, 1, 1)
        self.mssql_TBL_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_29)
        self.mssql_TBL_checkBox.setObjectName(_fromUtf8("mssql_TBL_checkBox"))
        self.gridLayout_29.addWidget(self.mssql_TBL_checkBox, 1, 0, 1, 1)
        self.mssql_TBL_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_29)
        self.mssql_TBL_lineEdit.setObjectName(_fromUtf8("mssql_TBL_lineEdit"))
        self.gridLayout_29.addWidget(self.mssql_TBL_lineEdit, 1, 1, 1, 1)
        self.mssql_DB_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_29)
        self.mssql_DB_checkBox.setObjectName(_fromUtf8("mssql_DB_checkBox"))
        self.gridLayout_29.addWidget(self.mssql_DB_checkBox, 0, 0, 1, 1)
        self.mssql_COL_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_29)
        self.mssql_COL_checkBox.setObjectName(_fromUtf8("mssql_COL_checkBox"))
        self.gridLayout_29.addWidget(self.mssql_COL_checkBox, 1, 2, 1, 1)
        self.mssql_COL_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_29)
        self.mssql_COL_lineEdit.setObjectName(_fromUtf8("mssql_COL_lineEdit"))
        self.gridLayout_29.addWidget(self.mssql_COL_lineEdit, 1, 3, 1, 1)
        self.tabWidget_17.addTab(self.tab_68, _fromUtf8(""))
        self.tab_69 = QtGui.QWidget()
        self.tab_69.setObjectName(_fromUtf8("tab_69"))
        self.formLayoutWidget_20 = QtGui.QWidget(self.tab_69)
        self.formLayoutWidget_20.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.formLayoutWidget_20.setObjectName(_fromUtf8("formLayoutWidget_20"))
        self.formLayout_20 = QtGui.QFormLayout(self.formLayoutWidget_20)
        self.formLayout_20.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_20.setMargin(0)
        self.formLayout_20.setObjectName(_fromUtf8("formLayout_20"))
        self.mssql_banner_checkBox = QtGui.QCheckBox(self.formLayoutWidget_20)
        self.mssql_banner_checkBox.setObjectName(_fromUtf8("mssql_banner_checkBox"))
        self.formLayout_20.setWidget(0, QtGui.QFormLayout.LabelRole, self.mssql_banner_checkBox)
        self.mssql_hostname_checkBox = QtGui.QCheckBox(self.formLayoutWidget_20)
        self.mssql_hostname_checkBox.setObjectName(_fromUtf8("mssql_hostname_checkBox"))
        self.formLayout_20.setWidget(1, QtGui.QFormLayout.LabelRole, self.mssql_hostname_checkBox)
        self.tabWidget_17.addTab(self.tab_69, _fromUtf8(""))
        self.tab_93 = QtGui.QWidget()
        self.tab_93.setObjectName(_fromUtf8("tab_93"))
        self.groupBox_19 = QtGui.QGroupBox(self.tab_93)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 10, 651, 81))
        self.groupBox_19.setTitle(_fromUtf8(""))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.mssql_sql_query_checkBox = QtGui.QCheckBox(self.groupBox_19)
        self.mssql_sql_query_checkBox.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.mssql_sql_query_checkBox.setObjectName(_fromUtf8("mssql_sql_query_checkBox"))
        self.mssql_sqlshell_checkBox = QtGui.QCheckBox(self.groupBox_19)
        self.mssql_sqlshell_checkBox.setGeometry(QtCore.QRect(10, 30, 201, 17))
        self.mssql_sqlshell_checkBox.setObjectName(_fromUtf8("mssql_sqlshell_checkBox"))
        self.mssql_sql_query_lineEdit = QtGui.QLineEdit(self.groupBox_19)
        self.mssql_sql_query_lineEdit.setGeometry(QtCore.QRect(230, 10, 401, 20))
        self.mssql_sql_query_lineEdit.setObjectName(_fromUtf8("mssql_sql_query_lineEdit"))
        self.tabWidget_17.addTab(self.tab_93, _fromUtf8(""))
        self.tab_70 = QtGui.QWidget()
        self.tab_70.setObjectName(_fromUtf8("tab_70"))
        self.mssql_brute_tables_checkBox = QtGui.QCheckBox(self.tab_70)
        self.mssql_brute_tables_checkBox.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.mssql_brute_tables_checkBox.setObjectName(_fromUtf8("mssql_brute_tables_checkBox"))
        self.mssql_brute_columns_checkBox = QtGui.QCheckBox(self.tab_70)
        self.mssql_brute_columns_checkBox.setGeometry(QtCore.QRect(10, 40, 151, 17))
        self.mssql_brute_columns_checkBox.setObjectName(_fromUtf8("mssql_brute_columns_checkBox"))
        self.tabWidget_17.addTab(self.tab_70, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget_17.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.mssql_current_user_checkBox.setText(_translate("Form", "Retrieve DBMS current user", None))
        self.mssql_passwords_checkBox.setText(_translate("Form", "Enumerate DBMS users password hashes", None))
        self.mssql_privileges_checkBox.setText(_translate("Form", "Enumerate DBMS users privileges", None))
        self.mssql_roles_checkBox.setText(_translate("Form", "Enumerate DBMS users roles", None))
        self.mssql_users_checkBox.setText(_translate("Form", "Enumerate DBMS users", None))
        self.mssql_is_dba_checkBox.setText(_translate("Form", "Detect if  current user is DBA", None))
        self.tabWidget_17.setTabText(self.tabWidget_17.indexOf(self.tab_65), _translate("Form", "Users", None))
        self.mssql_schema_checkBox.setText(_translate("Form", "Enumerate DBMS schema", None))
        self.mssql_columns_checkBox.setText(_translate("Form", "Enumerate DBMS database table columns", None))
        self.mssql_count_checkBox.setText(_translate("Form", "Retrieve number of entries for table(s)", None))
        self.mssql_dbs_checkBox.setText(_translate("Form", "Enumerate DBMS databases", None))
        self.mssql_tables_checkBox.setText(_translate("Form", "Enumerate DBMS database tables", None))
        self.tabWidget_17.setTabText(self.tabWidget_17.indexOf(self.tab_66), _translate("Form", "Databases", None))
        self.mssql_dump_all_checkBox.setText(_translate("Form", "Dump all DBMS databases tables entries", None))
        self.mssql_dump_checkBox.setText(_translate("Form", "Dump DBMS database table entries", None))
        self.tabWidget_17.setTabText(self.tabWidget_17.indexOf(self.tab_67), _translate("Form", "Entries", None))
        self.mssql_search_checkBox.setText(_translate("Form", "Search column(s), table(s) and/or database name(s)", None))
        self.mssql_TBL_checkBox.setText(_translate("Form", "DBMS db tables to enumerate", None))
        self.mssql_DB_checkBox.setText(_translate("Form", "DBMS db to enumerate", None))
        self.mssql_COL_checkBox.setText(_translate("Form", "DBMS db columns to enumerate", None))
        self.tabWidget_17.setTabText(self.tabWidget_17.indexOf(self.tab_68), _translate("Form", "Search", None))
        self.mssql_banner_checkBox.setText(_translate("Form", "Retrieve DBMS banner", None))
        self.mssql_hostname_checkBox.setText(_translate("Form", "Retrieve DBMS server hostname", None))
        self.tabWidget_17.setTabText(self.tabWidget_17.indexOf(self.tab_69), _translate("Form", "Generic", None))
        self.mssql_sql_query_checkBox.setText(_translate("Form", "SQL statement to be executed", None))
        self.mssql_sqlshell_checkBox.setText(_translate("Form", "Prompt for an interactive SQL shell", None))
        self.tabWidget_17.setTabText(self.tabWidget_17.indexOf(self.tab_93), _translate("Form", "Custom ", None))
        self.mssql_brute_tables_checkBox.setText(_translate("Form", "Check of common tables", None))
        self.mssql_brute_columns_checkBox.setText(_translate("Form", "Check  of common columns", None))
        self.tabWidget_17.setTabText(self.tabWidget_17.indexOf(self.tab_70), _translate("Form", "Brute force", None))

