# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oracle.ui'
#
# Created: Mon Oct 10 04:14:59 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormOracle(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(899, 656)
        self.tabWidget_11 = QtGui.QTabWidget(Form)
        self.tabWidget_11.setGeometry(QtCore.QRect(0, 0, 791, 147))# 0, 0, 791, 141
        self.tabWidget_11.setObjectName(_fromUtf8("tabWidget_11"))
        self.tab_34 = QtGui.QWidget()
        self.tab_34.setObjectName(_fromUtf8("tab_34"))
        self.tabWidget_12 = QtGui.QTabWidget(self.tab_34)
        self.tabWidget_12.setGeometry(QtCore.QRect(0, 0, 771, 120))
        self.tabWidget_12.setObjectName(_fromUtf8("tabWidget_12"))
        self.tab_45 = QtGui.QWidget()
        self.tab_45.setObjectName(_fromUtf8("tab_45"))
        self.gridLayoutWidget_16 = QtGui.QWidget(self.tab_45)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(10, 10, 741, 51))
        self.gridLayoutWidget_16.setObjectName(_fromUtf8("gridLayoutWidget_16"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.oracle_current_user_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_16)
        self.oracle_current_user_checkBox.setObjectName(_fromUtf8("oracle_current_user_checkBox"))
        self.gridLayout_16.addWidget(self.oracle_current_user_checkBox, 0, 0, 1, 1)
        self.oracle_roles_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_16)
        self.oracle_roles_checkBox.setObjectName(_fromUtf8("oracle_roles_checkBox"))
        self.gridLayout_16.addWidget(self.oracle_roles_checkBox, 0, 1, 1, 1)
        self.oracle_passwords_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_16)
        self.oracle_passwords_checkBox.setObjectName(_fromUtf8("oracle_passwords_checkBox"))
        self.gridLayout_16.addWidget(self.oracle_passwords_checkBox, 1, 0, 1, 1)
        self.oracle_privileges_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_16)
        self.oracle_privileges_checkBox.setObjectName(_fromUtf8("oracle_privileges_checkBox"))
        self.gridLayout_16.addWidget(self.oracle_privileges_checkBox, 0, 2, 1, 1)
        self.oracle_is_dba_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_16)
        self.oracle_is_dba_checkBox.setObjectName(_fromUtf8("oracle_is_dba_checkBox"))
        self.gridLayout_16.addWidget(self.oracle_is_dba_checkBox, 1, 1, 1, 1)
        self.oracle_users_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_16)
        self.oracle_users_checkBox.setObjectName(_fromUtf8("oracle_users_checkBox"))
        self.gridLayout_16.addWidget(self.oracle_users_checkBox, 1, 2, 1, 1)
        self.tabWidget_12.addTab(self.tab_45, _fromUtf8(""))
        self.tab_46 = QtGui.QWidget()
        self.tab_46.setObjectName(_fromUtf8("tab_46"))
        self.gridLayoutWidget_20 = QtGui.QWidget(self.tab_46)
        self.gridLayoutWidget_20.setGeometry(QtCore.QRect(20, 10, 731, 81))
        self.gridLayoutWidget_20.setObjectName(_fromUtf8("gridLayoutWidget_20"))
        self.gridLayout_20 = QtGui.QGridLayout(self.gridLayoutWidget_20)
        self.gridLayout_20.setMargin(0)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.oracle_tables_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_20)
        self.oracle_tables_checkBox.setObjectName(_fromUtf8("oracle_tables_checkBox"))
        self.gridLayout_20.addWidget(self.oracle_tables_checkBox, 2, 0, 1, 1)
        self.oracle_count_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_20)
        self.oracle_count_checkBox.setObjectName(_fromUtf8("oracle_count_checkBox"))
        self.gridLayout_20.addWidget(self.oracle_count_checkBox, 0, 0, 1, 1)
        self.oracle_columns_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_20)
        self.oracle_columns_checkBox.setObjectName(_fromUtf8("oracle_columns_checkBox"))
        self.gridLayout_20.addWidget(self.oracle_columns_checkBox, 1, 0, 1, 1)
        self.oracle_schema_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_20)
        self.oracle_schema_checkBox.setObjectName(_fromUtf8("oracle_schema_checkBox"))
        self.gridLayout_20.addWidget(self.oracle_schema_checkBox, 0, 1, 1, 1)
        self.oracle_dbs_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_20)
        self.oracle_dbs_checkBox.setObjectName(_fromUtf8("oracle_dbs_checkBox"))
        self.gridLayout_20.addWidget(self.oracle_dbs_checkBox, 1, 1, 1, 1)
        self.tabWidget_12.addTab(self.tab_46, _fromUtf8(""))
        self.tab_47 = QtGui.QWidget()
        self.tab_47.setObjectName(_fromUtf8("tab_47"))
        self.formLayoutWidget_15 = QtGui.QWidget(self.tab_47)
        self.formLayoutWidget_15.setGeometry(QtCore.QRect(10, 10, 222, 61))
        self.formLayoutWidget_15.setObjectName(_fromUtf8("formLayoutWidget_15"))
        self.formLayout_15 = QtGui.QFormLayout(self.formLayoutWidget_15)
        self.formLayout_15.setMargin(0)
        self.formLayout_15.setObjectName(_fromUtf8("formLayout_15"))
        self.oracle_dump_all_checkBox = QtGui.QCheckBox(self.formLayoutWidget_15)
        self.oracle_dump_all_checkBox.setObjectName(_fromUtf8("oracle_dump_all_checkBox"))
        self.formLayout_15.setWidget(2, QtGui.QFormLayout.LabelRole, self.oracle_dump_all_checkBox)
        self.oracle_dump_checkBox = QtGui.QCheckBox(self.formLayoutWidget_15)
        self.oracle_dump_checkBox.setObjectName(_fromUtf8("oracle_dump_checkBox"))
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.LabelRole, self.oracle_dump_checkBox)
        self.tabWidget_12.addTab(self.tab_47, _fromUtf8(""))
        self.tab_48 = QtGui.QWidget()
        self.tab_48.setObjectName(_fromUtf8("tab_48"))
        self.oracle_search_checkBox = QtGui.QCheckBox(self.tab_48)
        self.oracle_search_checkBox.setGeometry(QtCore.QRect(20, 10, 274, 17))
        self.oracle_search_checkBox.setObjectName(_fromUtf8("oracle_search_checkBox"))
        self.gridLayoutWidget_21 = QtGui.QWidget(self.tab_48)
        self.gridLayoutWidget_21.setGeometry(QtCore.QRect(20, 30, 731, 51))
        self.gridLayoutWidget_21.setObjectName(_fromUtf8("gridLayoutWidget_21"))
        self.gridLayout_21 = QtGui.QGridLayout(self.gridLayoutWidget_21)
        self.gridLayout_21.setMargin(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.oracle_DB_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_21)
        self.oracle_DB_checkBox.setObjectName(_fromUtf8("oracle_DB_checkBox"))
        self.gridLayout_21.addWidget(self.oracle_DB_checkBox, 0, 0, 1, 1)
        self.oracle_TBL_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_21)
        self.oracle_TBL_lineEdit.setObjectName(_fromUtf8("oracle_TBL_lineEdit"))
        self.gridLayout_21.addWidget(self.oracle_TBL_lineEdit, 1, 1, 1, 1)
        self.oracle_TBL_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_21)
        self.oracle_TBL_checkBox.setObjectName(_fromUtf8("oracle_TBL_checkBox"))
        self.gridLayout_21.addWidget(self.oracle_TBL_checkBox, 1, 0, 1, 1)
        self.oracle_DB_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_21)
        self.oracle_DB_lineEdit.setObjectName(_fromUtf8("oracle_DB_lineEdit"))
        self.gridLayout_21.addWidget(self.oracle_DB_lineEdit, 0, 1, 1, 1)
        self.oracle_COL_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_21)
        self.oracle_COL_checkBox.setObjectName(_fromUtf8("oracle_COL_checkBox"))
        self.gridLayout_21.addWidget(self.oracle_COL_checkBox, 1, 2, 1, 1)
        self.oracle_COL_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_21)
        self.oracle_COL_lineEdit.setObjectName(_fromUtf8("oracle_COL_lineEdit"))
        self.gridLayout_21.addWidget(self.oracle_COL_lineEdit, 1, 3, 1, 1)
        self.tabWidget_12.addTab(self.tab_48, _fromUtf8(""))
        self.tab_49 = QtGui.QWidget()
        self.tab_49.setObjectName(_fromUtf8("tab_49"))
        self.formLayoutWidget_16 = QtGui.QWidget(self.tab_49)
        self.formLayoutWidget_16.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.formLayoutWidget_16.setObjectName(_fromUtf8("formLayoutWidget_16"))
        self.formLayout_16 = QtGui.QFormLayout(self.formLayoutWidget_16)
        self.formLayout_16.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_16.setMargin(0)
        self.formLayout_16.setObjectName(_fromUtf8("formLayout_16"))
        self.oracle_banner_checkBox = QtGui.QCheckBox(self.formLayoutWidget_16)
        self.oracle_banner_checkBox.setObjectName(_fromUtf8("oracle_banner_checkBox"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.LabelRole, self.oracle_banner_checkBox)
        self.oracle_hostname_checkBox = QtGui.QCheckBox(self.formLayoutWidget_16)
        self.oracle_hostname_checkBox.setObjectName(_fromUtf8("oracle_hostname_checkBox"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.LabelRole, self.oracle_hostname_checkBox)
        self.tabWidget_12.addTab(self.tab_49, _fromUtf8(""))
        self.tab_95 = QtGui.QWidget()
        self.tab_95.setObjectName(_fromUtf8("tab_95"))
        self.groupBox_21 = QtGui.QGroupBox(self.tab_95)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 10, 741, 81))
        self.groupBox_21.setTitle(_fromUtf8(""))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.oracle_sql_query_checkBox = QtGui.QCheckBox(self.groupBox_21)
        self.oracle_sql_query_checkBox.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.oracle_sql_query_checkBox.setObjectName(_fromUtf8("oracle_sql_query_checkBox"))
        self.oracle_sqlshell_checkBox = QtGui.QCheckBox(self.groupBox_21)
        self.oracle_sqlshell_checkBox.setGeometry(QtCore.QRect(10, 30, 201, 17))
        self.oracle_sqlshell_checkBox.setObjectName(_fromUtf8("oracle_sqlshell_checkBox"))
        self.oracle_sqlfile_checkBox = QtGui.QCheckBox(self.groupBox_21)
        self.oracle_sqlfile_checkBox.setGeometry(QtCore.QRect(10, 50, 221, 17))
        self.oracle_sqlfile_checkBox.setObjectName(_fromUtf8("oracle_sqlfile_checkBox"))
        self.oracle_sql_query_lineEdit = QtGui.QLineEdit(self.groupBox_21)
        self.oracle_sql_query_lineEdit.setGeometry(QtCore.QRect(230, 10, 491, 20))
        self.oracle_sql_query_lineEdit.setObjectName(_fromUtf8("oracle_sql_query_lineEdit"))
        self.oracle_sqlfile_lineEdit = QtGui.QLineEdit(self.groupBox_21)
        self.oracle_sqlfile_lineEdit.setGeometry(QtCore.QRect(230, 50, 491, 20))
        self.oracle_sqlfile_lineEdit.setObjectName(_fromUtf8("oracle_sqlfile_lineEdit"))
        self.tabWidget_12.addTab(self.tab_95, _fromUtf8(""))
        self.tab_50 = QtGui.QWidget()
        self.tab_50.setObjectName(_fromUtf8("tab_50"))
        self.oracle_brute_tables_checkBox = QtGui.QCheckBox(self.tab_50)
        self.oracle_brute_tables_checkBox.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.oracle_brute_tables_checkBox.setObjectName(_fromUtf8("oracle_brute_tables_checkBox"))
        self.oracle_brute_columns_checkBox = QtGui.QCheckBox(self.tab_50)
        self.oracle_brute_columns_checkBox.setGeometry(QtCore.QRect(10, 40, 151, 17))
        self.oracle_brute_columns_checkBox.setObjectName(_fromUtf8("oracle_brute_columns_checkBox"))
        self.tabWidget_12.addTab(self.tab_50, _fromUtf8(""))
        self.tabWidget_11.addTab(self.tab_34, _fromUtf8(""))
        self.tab_44 = QtGui.QWidget()
        self.tab_44.setObjectName(_fromUtf8("tab_44"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_44)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 20, 751, 80))
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.oracle_fingerprint_checkBox = QtGui.QCheckBox(self.groupBox_9)
        self.oracle_fingerprint_checkBox.setGeometry(QtCore.QRect(10, 30, 281, 17))
        self.oracle_fingerprint_checkBox.setObjectName(_fromUtf8("oracle_fingerprint_checkBox"))
        self.tabWidget_11.addTab(self.tab_44, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget_11.setCurrentIndex(0)
        self.tabWidget_12.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.oracle_current_user_checkBox.setText(_translate("Form", "Retrieve DBMS current user", None))
        self.oracle_roles_checkBox.setText(_translate("Form", "Enumerate DBMS users roles", None))
        self.oracle_passwords_checkBox.setText(_translate("Form", "Enumerate DBMS users password hashes", None))
        self.oracle_privileges_checkBox.setText(_translate("Form", "Enumerate DBMS users privileges", None))
        self.oracle_is_dba_checkBox.setText(_translate("Form", "Detect if  current user is DBA", None))
        self.oracle_users_checkBox.setText(_translate("Form", "Enumerate DBMS users", None))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.tab_45), _translate("Form", "Users", None))
        self.oracle_tables_checkBox.setText(_translate("Form", "Enumerate DBMS database tables", None))
        self.oracle_count_checkBox.setText(_translate("Form", "Retrieve number of entries for table(s)", None))
        self.oracle_columns_checkBox.setText(_translate("Form", "Enumerate DBMS database table columns", None))
        self.oracle_schema_checkBox.setText(_translate("Form", "Enumerate DBMS schema", None))
        self.oracle_dbs_checkBox.setText(_translate("Form", "Enumerate DBMS databases", None))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.tab_46), _translate("Form", "Databases", None))
        self.oracle_dump_all_checkBox.setText(_translate("Form", "Dump all DBMS databases tables entries", None))
        self.oracle_dump_checkBox.setText(_translate("Form", "Dump DBMS database table entries", None))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.tab_47), _translate("Form", "Entries", None))
        self.oracle_search_checkBox.setText(_translate("Form", "Search column(s), table(s) and/or database name(s)", None))
        self.oracle_DB_checkBox.setText(_translate("Form", "DBMS db to enumerate", None))
        self.oracle_TBL_checkBox.setText(_translate("Form", "DBMS db tables to enumerate", None))
        self.oracle_COL_checkBox.setText(_translate("Form", "DBMS db columns to enumerate", None))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.tab_48), _translate("Form", "Search", None))
        self.oracle_banner_checkBox.setText(_translate("Form", "Retrieve DBMS banner", None))
        self.oracle_hostname_checkBox.setText(_translate("Form", "Retrieve DBMS server hostname", None))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.tab_49), _translate("Form", "Generic", None))
        self.oracle_sql_query_checkBox.setText(_translate("Form", "SQL statement to be executed", None))
        self.oracle_sqlshell_checkBox.setText(_translate("Form", "Prompt for an interactive SQL shell", None))
        self.oracle_sqlfile_checkBox.setText(_translate("Form", "Execute SQL statements from given file", None))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.tab_95), _translate("Form", "Custom", None))
        self.oracle_brute_tables_checkBox.setText(_translate("Form", "Check of common tables", None))
        self.oracle_brute_columns_checkBox.setText(_translate("Form", "Check  of common columns", None))
        self.tabWidget_12.setTabText(self.tabWidget_12.indexOf(self.tab_50), _translate("Form", "Brute force", None))
        self.tabWidget_11.setTabText(self.tabWidget_11.indexOf(self.tab_34), _translate("Form", "Enumeration", None))
        self.oracle_fingerprint_checkBox.setText(_translate("Form", "Extensive database management system fingerprint", None))
        self.tabWidget_11.setTabText(self.tabWidget_11.indexOf(self.tab_44), _translate("Form", "Fingerprint", None))

