# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlite.ui'
#
# Created: Mon Oct 10 04:11:06 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormSqlite(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(899, 656)
        self.tabWidget_22 = QtGui.QTabWidget(Form)
        self.tabWidget_22.setGeometry(QtCore.QRect(0, 0, 781, 151))
        self.tabWidget_22.setObjectName(_fromUtf8("tabWidget_22"))
        self.tab_98 = QtGui.QWidget()
        self.tab_98.setObjectName(_fromUtf8("tab_98"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_98)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 771, 121))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_29 = QtGui.QWidget()
        self.tab_29.setObjectName(_fromUtf8("tab_29"))
        self.gridLayoutWidget_13 = QtGui.QWidget(self.tab_29)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.gridLayoutWidget_13.setObjectName(_fromUtf8("gridLayoutWidget_13"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.sqlite_roles_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_13)
        self.sqlite_roles_checkBox.setObjectName(_fromUtf8("sqlite_roles_checkBox"))
        self.gridLayout_13.addWidget(self.sqlite_roles_checkBox, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_29, _fromUtf8(""))
        self.tab_32 = QtGui.QWidget()
        self.tab_32.setObjectName(_fromUtf8("tab_32"))
        self.gridLayoutWidget_15 = QtGui.QWidget(self.tab_32)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(20, 10, 731, 61))
        self.gridLayoutWidget_15.setObjectName(_fromUtf8("gridLayoutWidget_15"))
        self.gridLayout_15 = QtGui.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.sqlite_count_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_15)
        self.sqlite_count_checkBox.setObjectName(_fromUtf8("sqlite_count_checkBox"))
        self.gridLayout_15.addWidget(self.sqlite_count_checkBox, 0, 0, 1, 1)
        self.sqlite_columns_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_15)
        self.sqlite_columns_checkBox.setObjectName(_fromUtf8("sqlite_columns_checkBox"))
        self.gridLayout_15.addWidget(self.sqlite_columns_checkBox, 1, 0, 1, 1)
        self.sqlite_schema_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_15)
        self.sqlite_schema_checkBox.setObjectName(_fromUtf8("sqlite_schema_checkBox"))
        self.gridLayout_15.addWidget(self.sqlite_schema_checkBox, 0, 1, 1, 1)
        self.sqlite_tables_checkBox = QtGui.QCheckBox(self.gridLayoutWidget_15)
        self.sqlite_tables_checkBox.setObjectName(_fromUtf8("sqlite_tables_checkBox"))
        self.gridLayout_15.addWidget(self.sqlite_tables_checkBox, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_32, _fromUtf8(""))
        self.tab_33 = QtGui.QWidget()
        self.tab_33.setObjectName(_fromUtf8("tab_33"))
        self.formLayoutWidget_11 = QtGui.QWidget(self.tab_33)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(10, 10, 222, 61))
        self.formLayoutWidget_11.setObjectName(_fromUtf8("formLayoutWidget_11"))
        self.formLayout_11 = QtGui.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_11.setMargin(0)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.sqlite_dump_all_checkBox = QtGui.QCheckBox(self.formLayoutWidget_11)
        self.sqlite_dump_all_checkBox.setObjectName(_fromUtf8("sqlite_dump_all_checkBox"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.sqlite_dump_all_checkBox)
        self.sqlite_dump_checkBox = QtGui.QCheckBox(self.formLayoutWidget_11)
        self.sqlite_dump_checkBox.setObjectName(_fromUtf8("sqlite_dump_checkBox"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.sqlite_dump_checkBox)
        self.tabWidget_2.addTab(self.tab_33, _fromUtf8(""))
        self.tab_35 = QtGui.QWidget()
        self.tab_35.setObjectName(_fromUtf8("tab_35"))
        self.formLayoutWidget_12 = QtGui.QWidget(self.tab_35)
        self.formLayoutWidget_12.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.formLayoutWidget_12.setObjectName(_fromUtf8("formLayoutWidget_12"))
        self.formLayout_12 = QtGui.QFormLayout(self.formLayoutWidget_12)
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setMargin(0)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.sqlite_banner_checkBox = QtGui.QCheckBox(self.formLayoutWidget_12)
        self.sqlite_banner_checkBox.setObjectName(_fromUtf8("sqlite_banner_checkBox"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.sqlite_banner_checkBox)
        self.tabWidget_2.addTab(self.tab_35, _fromUtf8(""))
        self.tab_97 = QtGui.QWidget()
        self.tab_97.setObjectName(_fromUtf8("tab_97"))
        self.groupBox_23 = QtGui.QGroupBox(self.tab_97)
        self.groupBox_23.setGeometry(QtCore.QRect(0, 0, 741, 71))
        self.groupBox_23.setTitle(_fromUtf8(""))
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.sqlite_sql_query_checkBox = QtGui.QCheckBox(self.groupBox_23)
        self.sqlite_sql_query_checkBox.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.sqlite_sql_query_checkBox.setObjectName(_fromUtf8("sqlite_sql_query_checkBox"))
        self.sqlite_sqlshell_checkBox = QtGui.QCheckBox(self.groupBox_23)
        self.sqlite_sqlshell_checkBox.setGeometry(QtCore.QRect(10, 30, 201, 17))
        self.sqlite_sqlshell_checkBox.setObjectName(_fromUtf8("sqlite_sqlshell_checkBox"))
        self.sqlite_sqlfile_checkBox = QtGui.QCheckBox(self.groupBox_23)
        self.sqlite_sqlfile_checkBox.setGeometry(QtCore.QRect(10, 50, 221, 17))
        self.sqlite_sqlfile_checkBox.setObjectName(_fromUtf8("sqlite_sqlfile_checkBox"))
        self.sqlite_sql_query_lineEdit = QtGui.QLineEdit(self.groupBox_23)
        self.sqlite_sql_query_lineEdit.setGeometry(QtCore.QRect(230, 10, 491, 20))
        self.sqlite_sql_query_lineEdit.setObjectName(_fromUtf8("sqlite_sql_query_lineEdit"))
        self.sqlite_sqlfile_lineEdit = QtGui.QLineEdit(self.groupBox_23)
        self.sqlite_sqlfile_lineEdit.setGeometry(QtCore.QRect(230, 50, 491, 20))
        self.sqlite_sqlfile_lineEdit.setObjectName(_fromUtf8("sqlite_sqlfile_lineEdit"))
        self.tabWidget_2.addTab(self.tab_97, _fromUtf8(""))
        self.tab_36 = QtGui.QWidget()
        self.tab_36.setObjectName(_fromUtf8("tab_36"))
        self.sqlite_brute_tables_checkBox = QtGui.QCheckBox(self.tab_36)
        self.sqlite_brute_tables_checkBox.setGeometry(QtCore.QRect(20, 20, 141, 20))
        self.sqlite_brute_tables_checkBox.setObjectName(_fromUtf8("sqlite_brute_tables_checkBox"))
        self.sqlite_brute_columns_checkBox = QtGui.QCheckBox(self.tab_36)
        self.sqlite_brute_columns_checkBox.setGeometry(QtCore.QRect(20, 50, 151, 17))
        self.sqlite_brute_columns_checkBox.setObjectName(_fromUtf8("sqlite_brute_columns_checkBox"))
        self.tabWidget_2.addTab(self.tab_36, _fromUtf8(""))
        self.tabWidget_22.addTab(self.tab_98, _fromUtf8(""))
        self.tab_99 = QtGui.QWidget()
        self.tab_99.setObjectName(_fromUtf8("tab_99"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_99)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 751, 41))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.sqlite_fingerprint_checkBox = QtGui.QCheckBox(self.groupBox_8)
        self.sqlite_fingerprint_checkBox.setGeometry(QtCore.QRect(10, 20, 281, 17))
        self.sqlite_fingerprint_checkBox.setObjectName(_fromUtf8("sqlite_fingerprint_checkBox"))
        self.tabWidget_22.addTab(self.tab_99, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget_22.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.sqlite_roles_checkBox.setText(_translate("Form", "Enumerate DBMS users roles", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_29), _translate("Form", "Enumeration users", None))
        self.sqlite_count_checkBox.setText(_translate("Form", "Retrieve number of entries for table(s)", None))
        self.sqlite_columns_checkBox.setText(_translate("Form", "Enumerate DBMS database table columns", None))
        self.sqlite_schema_checkBox.setText(_translate("Form", "Enumerate DBMS schema", None))
        self.sqlite_tables_checkBox.setText(_translate("Form", "Enumerate DBMS database tables", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_32), _translate("Form", "Enumeration DB", None))
        self.sqlite_dump_all_checkBox.setText(_translate("Form", "Dump all DBMS databases tables entries", None))
        self.sqlite_dump_checkBox.setText(_translate("Form", "Dump DBMS database table entries", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_33), _translate("Form", "Enumeration entries", None))
        self.sqlite_banner_checkBox.setText(_translate("Form", "Retrieve DBMS banner", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_35), _translate("Form", "Enumeration generic", None))
        self.sqlite_sql_query_checkBox.setText(_translate("Form", "SQL statement to be executed", None))
        self.sqlite_sqlshell_checkBox.setText(_translate("Form", "Prompt for an interactive SQL shell", None))
        self.sqlite_sqlfile_checkBox.setText(_translate("Form", "Execute SQL statements from given file", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_97), _translate("Form", "Custom", None))
        self.sqlite_brute_tables_checkBox.setText(_translate("Form", "Check of common tables", None))
        self.sqlite_brute_columns_checkBox.setText(_translate("Form", "Check  of common columns", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_36), _translate("Form", "Brute force", None))
        self.tabWidget_22.setTabText(self.tabWidget_22.indexOf(self.tab_98), _translate("Form", "Enumeration", None))
        self.groupBox_8.setTitle(_translate("Form", "Fingerprint", None))
        self.sqlite_fingerprint_checkBox.setText(_translate("Form", "Extensive database management system fingerprint", None))
        self.tabWidget_22.setTabText(self.tabWidget_22.indexOf(self.tab_99), _translate("Form", "Fingerprint", None))

